#!/bin/bash
# Autonomous Script Generated by Jules for High-Impact Visuals
# This script uses the paperbanana CLI to generate three critical artifacts:
# 1. Complex Mechanism: IEC Bifurcation
# 2. Key Result: Thermodynamic Phase Diagram
# 3. Visual Abstract: Biological Countercurvature of Spacetime

# Ensure output directories exist
mkdir -p research/figures/

# 1. Complex Mechanism Diagram: IEC Feedback Loop and Bifurcation
paperbanana generate --input research/figures/jules_mechanism_iec_bifurcation.txt --caption 'IEC Feedback Loop and Supercritical Bifurcation' --output research/figures/jules_mechanism_iec_bifurcation.png

# 2. Key Result Plot: Thermodynamic Phase Diagram
paperbanana plot --data outputs/thermodynamic_cost/phase_diagram_energy_deficit_for_plot.csv --intent 'Plot a heatmap mapping L (Spinal Length) to the X-axis, chi_kappa (Coupling Strength) to the Y-axis, and R_deficit (Energy Deficit Ratio) as the color intensity. Use the viridis colormap and log scale if necessary. Label axes clearly.' --output research/figures/jules_thermodynamic_phase_diagram.png

# 3. Visual Abstract Diagram: Biological Countercurvature of Spacetime
paperbanana generate --input research/figures/jules_visual_abstract_bcs.txt --caption 'Visual Abstract: Biological Countercurvature of Spacetime' --output research/figures/jules_visual_abstract_bcs.png

echo "Pipeline complete."
