#!/usr/bin/env python3
"""
Validate open SpineWeb/AASCE landmark geometry endpoints.

This script consumes the landmark feature table generated by
open_data_spineweb_features.py and produces a publication-facing validation
package. The evidence target is intentionally limited to 2D landmark geometry:
derived Cobb-like endplate envelope, centerline deviation, tortuosity, and
projected rotation proxies.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats


PROJECT_DIR = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_DIR / "results" / "open_data"
FEATURES_CSV = RESULTS_DIR / "spineweb_landmark_features.csv"

SUMMARY_JSON = RESULTS_DIR / "spineweb_geometry_validation_summary.json"
OUTLIERS_CSV = RESULTS_DIR / "spineweb_geometry_validation_outliers.csv"
PANELS_PNG = RESULTS_DIR / "spineweb_geometry_validation_panels.png"
REPORT_MD = RESULTS_DIR / "spineweb_geometry_validation_report.md"

PRIMARY_ENDPOINT = "cobb_endplate_envelope_deg"
METRIC_COLUMNS = [
    "max_chord_deviation_norm",
    "lateral_span_norm",
    "projected_rotation_total_deg",
    "projected_curvature_energy",
    "tortuosity",
    "centerline_cobb_like_deg",
]


def finite_frame(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    out = df.copy()
    for column in columns:
        out[column] = pd.to_numeric(out[column], errors="coerce")
    mask = np.isfinite(out[columns].to_numpy(dtype=float)).all(axis=1)
    return out.loc[mask].copy()


def fisher_ci(value: float, n: int, alpha: float = 0.05) -> tuple[float, float]:
    """Approximate Fisher-z confidence interval for a correlation coefficient."""
    if n <= 3 or not np.isfinite(value):
        return (float("nan"), float("nan"))
    bounded = float(np.clip(value, -0.999999, 0.999999))
    z = np.arctanh(bounded)
    se = 1.0 / math.sqrt(n - 3)
    zcrit = float(stats.norm.ppf(1.0 - alpha / 2.0))
    return (float(np.tanh(z - zcrit * se)), float(np.tanh(z + zcrit * se)))


def quantiles(series: pd.Series) -> dict[str, float]:
    q = series.quantile([0.05, 0.25, 0.5, 0.75, 0.95])
    return {str(k): float(v) for k, v in q.items()}


def correlation_summary(df: pd.DataFrame) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for metric in METRIC_COLUMNS:
        paired = finite_frame(df, [PRIMARY_ENDPOINT, metric])
        x = paired[PRIMARY_ENDPOINT].to_numpy(dtype=float)
        y = paired[metric].to_numpy(dtype=float)
        n = int(len(paired))
        if n < 4:
            continue

        pearson = stats.pearsonr(x, y)
        spearman = stats.spearmanr(x, y)
        pearson_ci = fisher_ci(float(pearson.statistic), n)
        spearman_ci = fisher_ci(float(spearman.statistic), n)
        rows.append(
            {
                "metric": metric,
                "n": n,
                "pearson_r": float(pearson.statistic),
                "pearson_p": float(pearson.pvalue),
                "pearson_ci95": [pearson_ci[0], pearson_ci[1]],
                "spearman_rho": float(spearman.statistic),
                "spearman_p": float(spearman.pvalue),
                "spearman_ci95_approx": [spearman_ci[0], spearman_ci[1]],
            }
        )
    rows.sort(key=lambda item: abs(float(item["spearman_rho"])), reverse=True)
    return rows


def group_summary(df: pd.DataFrame, group_col: str) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for raw_label, group in df.groupby(group_col, dropna=False):
        label = str(raw_label) if str(raw_label) else "unlabeled"
        out[label] = {
            "n": int(len(group)),
            "cobb_median": float(group[PRIMARY_ENDPOINT].median()),
            "cobb_iqr": [
                float(group[PRIMARY_ENDPOINT].quantile(0.25)),
                float(group[PRIMARY_ENDPOINT].quantile(0.75)),
            ],
            "max_chord_deviation_median": float(group["max_chord_deviation_norm"].median()),
            "projected_rotation_median": float(group["projected_rotation_total_deg"].median()),
        }
    return out


def quality_sensitivity(df: pd.DataFrame) -> dict[str, Any]:
    good = df[df["annotation_quality"] == "good"][PRIMARY_ENDPOINT]
    nongood = df[df["annotation_quality"] != "good"][PRIMARY_ENDPOINT]
    result: dict[str, Any] = {
        "good_n": int(len(good)),
        "non_good_n": int(len(nongood)),
        "good_median": float(good.median()) if len(good) else float("nan"),
        "non_good_median": float(nongood.median()) if len(nongood) else float("nan"),
    }
    if len(good) > 0 and len(nongood) > 0:
        test = stats.mannwhitneyu(good, nongood, alternative="two-sided")
        result["mann_whitney_u"] = float(test.statistic)
        result["mann_whitney_p"] = float(test.pvalue)
    return result


def residual_outliers(df: pd.DataFrame, n_cases: int = 20) -> pd.DataFrame:
    paired = finite_frame(df, [PRIMARY_ENDPOINT, "max_chord_deviation_norm"])
    x = paired[PRIMARY_ENDPOINT].to_numpy(dtype=float)
    y = paired["max_chord_deviation_norm"].to_numpy(dtype=float)
    slope, intercept = np.polyfit(x, y, deg=1)
    predicted = slope * x + intercept
    residual = y - predicted
    scale = float(np.std(residual, ddof=1))
    z = residual / scale if scale > 0.0 else residual * 0.0

    out = paired.copy()
    out["deviation_residual"] = residual
    out["deviation_residual_z"] = z
    out["manual_review_reason"] = np.where(
        out["deviation_residual_z"] > 0.0,
        "more centerline deviation than expected from Cobb-like angle",
        "less centerline deviation than expected from Cobb-like angle",
    )
    cols = [
        "split",
        "xml_file",
        "input_file",
        "annotation_quality",
        "correction_state",
        PRIMARY_ENDPOINT,
        "max_chord_deviation_norm",
        "lateral_span_norm",
        "projected_rotation_total_deg",
        "tortuosity",
        "cobb_plate_a",
        "cobb_plate_b",
        "deviation_residual",
        "deviation_residual_z",
        "manual_review_reason",
    ]
    return out.assign(abs_z=np.abs(out["deviation_residual_z"])).sort_values("abs_z", ascending=False)[cols].head(n_cases)


def threshold_counts(df: pd.DataFrame) -> dict[str, int]:
    return {
        "cobb_ge_10": int((df[PRIMARY_ENDPOINT] >= 10.0).sum()),
        "cobb_ge_20": int((df[PRIMARY_ENDPOINT] >= 20.0).sum()),
        "cobb_ge_40": int((df[PRIMARY_ENDPOINT] >= 40.0).sum()),
    }


def build_summary(df: pd.DataFrame, outliers: pd.DataFrame) -> dict[str, Any]:
    usable = df[df["is_usable"]].copy()
    complete_usable = usable[usable["is_complete_t1_l5"]].copy()
    correlations = correlation_summary(usable)
    summary: dict[str, Any] = {
        "dataset": "SpineWeb/AASCE 2019 curated landmark annotations",
        "source": "https://zenodo.org/records/4413665",
        "evidence_level": "landmark-only 2D geometry validation",
        "primary_endpoint": PRIMARY_ENDPOINT,
        "n_cases_total": int(len(df)),
        "n_train": int((df["split"] == "train").sum()),
        "n_test": int((df["split"] == "test").sum()),
        "n_usable": int(len(usable)),
        "n_complete_t1_l5": int(df["is_complete_t1_l5"].sum()),
        "n_usable_complete_t1_l5": int(len(complete_usable)),
        "threshold_counts_usable": threshold_counts(usable),
        "primary_endpoint_quantiles_usable": quantiles(usable[PRIMARY_ENDPOINT]),
        "metric_quantiles_usable": {metric: quantiles(usable[metric]) for metric in METRIC_COLUMNS},
        "correlations_vs_primary_endpoint": correlations,
        "annotation_quality_summary_usable": group_summary(usable, "annotation_quality"),
        "split_summary_usable": group_summary(usable, "split"),
        "quality_sensitivity": quality_sensitivity(usable),
        "outlier_review": {
            "method": "largest absolute residuals from linear fit of normalized chord deviation on Cobb-like endplate envelope",
            "n_cases": int(len(outliers)),
            "csv": str(OUTLIERS_CSV),
        },
        "limitations": [
            "No image pixels are required for this analysis.",
            "Cobb-like values are derived from landmarks, not independent clinician measurements.",
            "Projected rotation and curvature metrics are 2D AP-projection proxies, not true 3D axial rotation.",
            "No growth stage, bracing exposure, or longitudinal progression endpoint is available in this open package.",
        ],
    }
    return summary


def boxplot_with_labels(ax: plt.Axes, values: list[np.ndarray], labels: list[str]) -> None:
    try:
        ax.boxplot(values, tick_labels=labels, showfliers=False)
    except TypeError:
        ax.boxplot(values, labels=labels, showfliers=False)


def write_panels(df: pd.DataFrame, correlations: list[dict[str, Any]], out_path: Path) -> None:
    usable = df[df["is_usable"]].copy()
    fig, axes = plt.subplots(2, 3, figsize=(13, 8.5))

    axes[0, 0].hist(usable[PRIMARY_ENDPOINT], bins=32, color="#4C78A8", edgecolor="white")
    for threshold in [10, 20, 40]:
        axes[0, 0].axvline(threshold, color="#E45756", linestyle="--", linewidth=1)
    axes[0, 0].set_title("Derived Cobb-like envelope")
    axes[0, 0].set_xlabel("Angle, degrees")
    axes[0, 0].set_ylabel("Usable cases")

    axes[0, 1].scatter(
        usable[PRIMARY_ENDPOINT],
        usable["max_chord_deviation_norm"],
        s=14,
        alpha=0.65,
        color="#54A24B",
        linewidths=0,
    )
    x = usable[PRIMARY_ENDPOINT].to_numpy(dtype=float)
    y = usable["max_chord_deviation_norm"].to_numpy(dtype=float)
    slope, intercept = np.polyfit(x, y, deg=1)
    grid = np.linspace(float(np.min(x)), float(np.max(x)), 100)
    axes[0, 1].plot(grid, slope * grid + intercept, color="#222222", linewidth=1.2)
    axes[0, 1].set_title("Cobb-like angle vs lateral deviation")
    axes[0, 1].set_xlabel("Angle, degrees")
    axes[0, 1].set_ylabel("Max chord deviation / vertical span")

    axes[0, 2].scatter(
        usable[PRIMARY_ENDPOINT],
        usable["projected_rotation_total_deg"],
        s=14,
        alpha=0.65,
        color="#F58518",
        linewidths=0,
    )
    axes[0, 2].set_title("Projected rotation proxy")
    axes[0, 2].set_xlabel("Angle, degrees")
    axes[0, 2].set_ylabel("Total centerline turn, degrees")

    corr_df = pd.DataFrame(correlations)
    corr_df = corr_df.sort_values("spearman_rho")
    axes[1, 0].barh(corr_df["metric"], corr_df["spearman_rho"], color="#72B7B2")
    axes[1, 0].axvline(0.0, color="#222222", linewidth=0.8)
    axes[1, 0].set_title("Spearman correlation vs Cobb-like angle")
    axes[1, 0].set_xlabel("rho")

    grouped = usable.groupby("annotation_quality")[PRIMARY_ENDPOINT]
    labels = [str(label) or "unlabeled" for label in grouped.groups]
    values = [grouped.get_group(label).to_numpy(dtype=float) for label in grouped.groups]
    boxplot_with_labels(axes[1, 1], values, labels)
    axes[1, 1].set_title("Angle by annotation quality")
    axes[1, 1].set_ylabel("Angle, degrees")
    axes[1, 1].tick_params(axis="x", rotation=20)

    axes[1, 2].scatter(
        usable["max_chord_deviation_norm"],
        usable["projected_curvature_energy"],
        s=14,
        alpha=0.65,
        color="#B279A2",
        linewidths=0,
    )
    axes[1, 2].set_title("Deviation vs curvature energy")
    axes[1, 2].set_xlabel("Max chord deviation / vertical span")
    axes[1, 2].set_ylabel("Projected curvature energy")

    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


def format_ci(values: list[float]) -> str:
    return f"[{values[0]:.3f}, {values[1]:.3f}]"


def write_report(summary: dict[str, Any], out_path: Path) -> None:
    correlations = summary["correlations_vs_primary_endpoint"]
    top = correlations[:4]
    threshold = summary["threshold_counts_usable"]
    q = summary["primary_endpoint_quantiles_usable"]
    lines = [
        "# SpineWeb Open Landmark Geometry Validation",
        "",
        "## Dataset",
        "",
        "This analysis uses the free SpineWeb/AASCE 2019 curated landmark annotations from Zenodo.",
        "The package contains T1-L5 quadrilateral landmarks for AP spine radiographs and correction-quality flags.",
        "",
        f"- Total cases: {summary['n_cases_total']}",
        f"- Train/test cases: {summary['n_train']} / {summary['n_test']}",
        f"- Usable cases by correction flags: {summary['n_usable']}",
        f"- Usable complete T1-L5 cases: {summary['n_usable_complete_t1_l5']}",
        "",
        "## Derived Endpoints",
        "",
        "The primary endpoint is `cobb_endplate_envelope_deg`, defined as the maximum acute angle between any two annotated vertebral endplate lines.",
        "Secondary endpoints quantify centerline shape in the AP projection: normalized lateral deviation, lateral span, tortuosity, total projected turn, projected curvature energy, and a centerline boundary-angle proxy.",
        "",
        "## Main Results",
        "",
        f"- Median derived Cobb-like envelope in usable cases: {q['0.5']:.2f} degrees.",
        f"- Interquartile range: {q['0.25']:.2f} to {q['0.75']:.2f} degrees.",
        f"- Usable cases with Cobb-like envelope >=10/20/40 degrees: {threshold['cobb_ge_10']} / {threshold['cobb_ge_20']} / {threshold['cobb_ge_40']}.",
        "",
        "Strongest rank correlations with the primary endpoint:",
        "",
    ]
    for row in top:
        lines.append(
            f"- `{row['metric']}`: Spearman rho={row['spearman_rho']:.3f}, "
            f"95% CI {format_ci(row['spearman_ci95_approx'])}, p={row['spearman_p']:.2e}, n={row['n']}"
        )

    quality = summary["quality_sensitivity"]
    lines.extend(
        [
            "",
            "## Quality Sensitivity",
            "",
            f"Good annotations had median Cobb-like envelope {quality['good_median']:.2f} degrees "
            f"(n={quality['good_n']}); non-good usable annotations had median {quality['non_good_median']:.2f} degrees "
            f"(n={quality['non_good_n']}).",
            f"Mann-Whitney U p-value for good vs non-good usable cases: {quality.get('mann_whitney_p', float('nan')):.3g}.",
            "",
            "## Interpretation",
            "",
            "This validates that the open landmark pipeline produces coherent geometric endpoints: derived endplate angle, lateral deviation, tortuosity, and projected curvature move together in the expected direction.",
            "It does not validate the full AIS progression mechanism because this open package lacks growth stage, treatment exposure, serial Cobb measurements, and progression labels.",
            "",
            "## Output Files",
            "",
            f"- Feature table: `{FEATURES_CSV}`",
            f"- Validation summary: `{SUMMARY_JSON}`",
            f"- Manual-review outliers: `{OUTLIERS_CSV}`",
            f"- Figure panels: `{PANELS_PNG}`",
            "",
        ]
    )
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    if not FEATURES_CSV.exists():
        raise FileNotFoundError(f"Feature table not found: {FEATURES_CSV}")

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(FEATURES_CSV)
    df = finite_frame(df, [PRIMARY_ENDPOINT] + METRIC_COLUMNS)

    outliers = residual_outliers(df[df["is_usable"]].copy())
    outliers.to_csv(OUTLIERS_CSV, index=False)

    summary = build_summary(df, outliers)
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    write_panels(df, summary["correlations_vs_primary_endpoint"], PANELS_PNG)
    write_report(summary, REPORT_MD)

    print(f"Wrote {SUMMARY_JSON}")
    print(f"Wrote {OUTLIERS_CSV}")
    print(f"Wrote {PANELS_PNG}")
    print(f"Wrote {REPORT_MD}")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
